download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/arubanetworks-aoscx-4.4.0.tar.gz
format_version: 1.0.0
name: aoscx
namespace: arubanetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.4.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/arubanetworks/aoscx/versions/4.4.0/
