all:
  children:
    clab_nodes:
      vars:
        lab_topo: "cx_basic"
      hosts:
        aoscx1:
          ansible_host: 172.20.20.10  # IP on clab network
          ansible_user: admin
          ansible_password: admin
          ansible_network_os: arubanetworks.aoscx.aoscx
          #ansible_connection: network_cli  # this is connection method using SSH
          ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx (Python SDK for aoscx) connection method
          ansible_aoscx_validate_certs: False
          ansible_aoscx_use_proxy: False
          ansible_acx_no_proxy: True
          # this will tell it not to use authorized key
          ansible_ssh_private_key_file: null
        aoscx2:
          ansible_host: 172.20.20.20  # IP on clab network
          ansible_user: admin
          ansible_password: admin
          ansible_network_os: arubanetworks.aoscx.aoscx
          #ansible_connection: network_cli  # this is connection method using SSH
          ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx (Python SDK for aoscx) connection method
          ansible_aoscx_validate_certs: False
          ansible_aoscx_use_proxy: False
          ansible_acx_no_proxy: True
          # this will tell it not to use authorized key
          ansible_ssh_private_key_file: null
        aoscx3:
          ansible_host: 172.20.20.30  # IP on clab network
          ansible_user: admin
          ansible_password: admin
          ansible_network_os: arubanetworks.aoscx.aoscx
          #ansible_connection: network_cli  # this is connection method using SSH
          ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx (Python SDK for aoscx) connection method
          ansible_aoscx_validate_certs: False
          ansible_aoscx_use_proxy: False
          ansible_acx_no_proxy: True
          # this will tell it not to use authorized key
          ansible_ssh_private_key_file: null