all:
  vars:
    lab_name: arubacx-and-host
  children:
    clab_nodes:
      hosts:
        cx1:
          ansible_host: 172.20.20.10
          ansible_user: admin
          ansible_password: admin
          ansible_network_os: arubanetworks.aoscx.aoscx
          ansible_connection: arubanetworks.aoscx.aoscx
          ansible_aoscx_validate_certs: false
          ansible_aoscx_use_proxy: false
          ansible_acx_no_proxy: true