- name: Backup Module Aruba-CX config
# this uses API to backup an running config and store locally as JSON
  hosts: clab_nodes
  gather_facts: no
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Copy Running Config to local as JSON # only works with JSON output
      aoscx_backup_config:
        config_name: running-config-json
        output_file: /ansible/documentation/running-config.txt
